"""added alerts table

Revision ID: 45455cd26d21
Revises: 324c3d121c01
Create Date: 2026-03-28 19:26:33.468244

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45455cd26d21"
down_revision: str | Sequence[str] | None = "324c3d121c01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("alert_type", sa.Enum("ERROR_SPIKE", name="alerttype"), nullable=False),
        sa.Column(
            "level", sa.Enum("HIGH", "CRITICAL", "SEVERE", name="alertlevel"), nullable=False
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_ids", sa.ARRAY(sa.UUID()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_expired", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("parent", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_parent"), "alerts", ["parent"], unique=False)
    op.create_index(op.f("ix_alerts_triggered_at"), "alerts", ["triggered_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alerts_triggered_at"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_parent"), table_name="alerts")
    op.drop_table("alerts")
    # ### end Alembic commands ###
