"""added occured at column to events table

Revision ID: 8ccc311eae1a
Revises: 45455cd26d21
Create Date: 2026-03-31 12:34:09.226926

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ccc311eae1a"
down_revision: str | Sequence[str] | None = "45455cd26d21"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("occurred_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "occurred_at")
    # ### end Alembic commands ###
